image:
  file: .gitpod.dockerfile

github:
  prebuilds:
    # enable for the master/default branch
    master: true
    # enable for all branches in this repo
    branches: true
    # enable for pull requests coming from this repo
    pullRequests: true
    # enable for pull requests coming from forks
    pullRequestsFromForks: true
    # add a check to pull requests
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description
    addBadge: true
    # add a label once the prebuild is ready to pull requests
    addLabel: true
