name: fluttermatic_api
description: A simple command-line application.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.17.4
dependencies:
  mongo_dart: ^0.7.0+2
  path: ^1.8.0
  shelf_router: ^1.0.0
  shelf_static: ^1.1.0
